-- MySQL Script generated by MySQL Workbench
-- jue 25 feb 2016 02:40:19 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stop_bad_files` ;

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stop_bad_files` ;
USE `stop_bad_files` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stop_bad_files`.`files` (
  `idfile` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(120) NOT NULL,
  `size` INT NOT NULL,
  `state` INT NOT NULL,
  `uidNumber` INT NOT NULL,
  `datetime` DATE NOT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `report` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idfile`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


